export const GET_COURSES = 'GET_ALL_COURSES';
export const COURSES_LOADING = 'COURSES_LOADING';
export const COURSE_DESCRIPTION = 'COURSE_DESCRIPTION';

export const GET_ERRORS = "GET_ERRORS";
export const CLEAR_ERRORS = "CLEAR_ERRORS";

export const COURSE_ENQUIRY = "COURSE_ENQUIRY";
export const COURSE_INFO = "COURSE_INFO";

export const GET_ALL_RESULTS = 'ALL_RESULTS';
export const GET_COURSE_RESULTS = 'COURSE_RESULTS';

export const CENTRE_INFO = "CENTRE_INFO";
export const GET_ALL_CENTRES = 'GET_ALL_CENTRES';
export const GET_CENTRE_BY_PLACE = 'GET_CENTRES_BY_PLACE';
export const GET_CENTRES_BY_COURSE = 'GET_CENTRES_BY_COURSE';

export const REGISTER_FAIL = 'REGISTER_FAIL';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const DELETE_EXPIRED_TEMP_USERS = 'DELETE_EXPIRED_TEMP_USERS';
export const VERIFY_SUCCESS = 'VERIFY_SUCCESS';
export const VERIFY_FAIL = 'VERIFY_FAIL';
